# Generated by Django 5.2.3 on 2025-06-16 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('mood', models.CharField(choices=[('Very Happy', 'Very Happy'), ('Happy', 'Happy'), ('Neutral', 'Neutral'), ('Sad', 'Sad')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
